### ISSUE TITLE
Wrong action name in readme

### ISSUE THREAD

**Issue by upikoth** [MrMeison/yc-object-storage-action#169]
Readme:

```yml
name: Deploy static website to Yandex Object Storage
on:
    push:
        branches:
            - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}    
            - name: Install NPM dependencies
              run: npm ci
    
            - name: Build application
              run: npm run build
    
            - uses: MrMeison/yc-object-storage-upload-action@main
              with:
                accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
                secretAccessKey: ${{ secrets.SECRET_ACCESS_KEY }}
                bucketName: ${{ secrets.BUCKET }}
                sourceDir: ./dist
                clear: true
```

current:
uses: MrMeison/yc-object-storage-upload-action@main

expected:
uses: MrMeison/yc-object-storage-action@main
