### ISSUE TITLE
An error was encountered in a non-retryable streaming request.

### ISSUE THREAD

**Issue by dympopov** [MrMeison/yc-object-storage-action#188]
Hi. Three days ago everything was fine, but today a problem arose. The deployment is going well. But when uploaded to Yandex Object with your script, an error occurs:

```
Starting to upload: assets/third-aQm6nE5V.png
An error was encountered in a non-retryable streaming request.
Error: Error: 
The provided 'x-amz-content-sha256' header does not match what was computed.
Error: The provided 'x-amz-content-sha256' header does not match what was computed.
An error was encountered in a non-retryable streaming request.
```

I saw that you updated the project two days ago. Maybe something critically changed?

Just in case, I'm attaching our yml and github logs

[logs_35245122336.zip](https://github.com/user-attachments/files/19092919/logs_35245122336.zip)

:

```
name: Example workflow for S3 Deploy
on:
  push:
    branches: ["dev", "cicd/**"]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: MrMeison/yc-object-storage-action@main
        with:
          accessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          sourceDir: dist
          bucketName: ${{ secrets.BUCKET }}
          clear: true
          includeDots: true

      - name: Purge CDN cache
        id: purge-cache
        uses: yc-actions/yc-cdn-cache@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_CDN_JSON_CREDENTIALS }}
          cdn-resource-id: xxxxxxxxxxxx
```
